name = "256-diary"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "256-diary-db"
database_id = "TODO"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "256-diary-images"
