name = "400-diary"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "400-diary-db"
database_id = "TODO"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "400-diary-images"

[vars]
CF_ACCESS_TEAM_DOMAIN = "YOUR_TEAM.cloudflareaccess.com"
CF_ACCESS_AUD = "YOUR_APPLICATION_AUD_TAG"
